resources:
- base/open-webui.yaml
- base/ollama-service.yaml
- base/ollama-statefulset.yaml
- base/webui-deployment.yaml
- base/webui-service.yaml
- base/webui-ingress.yaml
- base/webui-pvc.yaml
- base/configmap.yaml
- base/virtualservice.yaml
- base/serviceaccount.yaml
- base/role.yaml
- base/rolebinding.yaml
- base/gateway.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/ollama-statefulset-gpu.yaml
